import Head from 'next/head'
import Image from 'next/image'
import type { NextPage, GetStaticProps } from "next"

import { Box, Grid } from "@chakra-ui/react"
import { Tabs, TabList, TabPanels, Tab, TabPanel } from '@chakra-ui/react'

import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'


import Item from '@/src/types/item'
import {load} from '@/src/loader'

const inter = Inter({ subsets: ['latin'] })

interface HomeProps {
  items: Array<Item>;
}

export async function getStaticProps() {
  // const files = fs.readdirSync(path.join('posts'))
  const items = load()
  return {
    props: { items }, // will be passed to the page component as props
  }
}

function categorizeItemsByStore(items : Array<Item>) {
  const storeItems : { [ storeName : string ] : Array<Item> } = {};

  items.forEach(( item : Item) => {
    const storeName = item.store

    if (storeItems[storeName]) {
      storeItems[storeName].push(item)
    } else {
      storeItems[storeName] = [item];
    }
  })

  return storeItems;
}

export default function Home(props : HomeProps) {
  const items = props.items;
  const allStoreItems = categorizeItemsByStore(items);

  console.log(allStoreItems);

  const storeNames = Object.keys(allStoreItems);

  return (
    <>
      <Head>
        <title>Simcity BuildIt - ProduceIt!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Tabs>
          <TabList>
            {
              storeNames.map((n : string) => {
                return <Tab key={n}>{n}</Tab>;
              })
            }
          </TabList>

          <TabPanels>
            {
              storeNames.map((n : string) => {
                const storeItems = allStoreItems[n]

                return <TabPanel key={n}>
                  <Grid gap={2} autoFlow="row dense">
                    {
                      storeItems.map(( item ) => {
                        return <div>
                          <Image
                            key={item.name}
                            src={ `/items/${item.name}.png` }
                            alt="13"
                            width={40}
                            height={31}
                            priority
                          />
                          {item.name}
                        </div>
                      })
                    }

                  </Grid>
                </TabPanel>;
              })
            }
          </TabPanels>
        </Tabs>
      </main>
    </>
  )
}
